parameters:
    mercure.jwt_secret: "%env(MERCURE_JWT_SECRET)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $mercureKey: "%mercure.jwt_secret%"

    App\Security\JWTAuthenticationSuccessHandler:
        arguments:
            $jwtManager: "@lexik_jwt_authentication.jwt_manager"

    App\EventListener\PropertyCreatedListener:
        tags:
            - {
                  name: "kernel.event_listener",
                  event: "property.created",
                  method: "onPropertyCreated",
              }

    App\EventListener\JWTFailureListener:
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_authentication_failure,
                  method: onAuthenticationFailureResponse,
              }

    App\Service\PaystackService:
        arguments:
            $paystackSecretKey: "%env(PAYSTACK_SECRET_KEY)%"

    App\:
        resource: "../src/"
